// <auto-generated />
using System;
using BookInventoryMgt.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookInventoryMgt.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20241107235408_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookInventoryMgt.Entities.Inventory", b =>
                {
                    b.Property<int>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EntryId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("PublicationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EntryId");

                    b.HasIndex("ISBN")
                        .IsUnique();

                    b.ToTable("Inventories");

                    b.HasData(
                        new
                        {
                            EntryId = 1,
                            Author = "Harper Lee",
                            Genre = "Fiction",
                            ISBN = "978-0-06-112008-4",
                            PublicationDate = new DateTime(2024, 11, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "To Kill a Mockingbird"
                        },
                        new
                        {
                            EntryId = 2,
                            Author = "George Orwell",
                            Genre = "Dystopian",
                            ISBN = "978-0-452-28423-4",
                            PublicationDate = new DateTime(2024, 11, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "1984"
                        },
                        new
                        {
                            EntryId = 3,
                            Author = "Jane Austen",
                            Genre = "Romance",
                            ISBN = "978-0-19-953556-9",
                            PublicationDate = new DateTime(2024, 11, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "Pride and Prejudice"
                        },
                        new
                        {
                            EntryId = 4,
                            Author = "F. Scott Fitzgerald",
                            Genre = "Tragedy",
                            ISBN = "978-0-7432-7356-5",
                            PublicationDate = new DateTime(2024, 11, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "The Great Gatsby"
                        },
                        new
                        {
                            EntryId = 5,
                            Author = "Stephen King",
                            Genre = "Horror",
                            ISBN = "978-0-385-12167-1",
                            PublicationDate = new DateTime(2024, 11, 7, 0, 0, 0, 0, DateTimeKind.Local),
                            Title = "The Shining"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
